fail_fast: false
repos:
-   repo: https://github.com/pocc/pre-commit-hooks 
    rev: v1.3.5
    hooks:
    -   id: clang-format
        args: [--style=Google]
        files: ^c/.*$
        types: [c]
    -   id: clang-tidy
        files: ^c/.*$
        types: [c]
    -   id: oclint
        files: ^c/.*$
        types: [c]
    -   id: uncrustify
        files: ^c/.*$
        types: [c]
    -   id: cppcheck
        files: ^c/.*$
        types: [c]
    -   id: cpplint
        files: ^c/.*$
        types: [c]
